name: Software Composition Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Run Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'auth-api'
          path: '.'
          format: 'HTML'
          out: 'reports'
          
      - name: Upload Test results
        uses: actions/upload-artifact@v4
        with:
          name: Dependency Check Report
          path: ${{github.workspace}}/reports/dependency-check-report.html
