name: Integrated Security Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  dast:
    name: DAST - OWASP ZAP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:8080'
        continue-on-error: true

      - name: List files for debug
        run: ls -lh

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html
        continue-on-error: true

  sca:
    name: SCA - Dependency-Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Dependency-Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.1/dependency-check-8.4.1-release.zip
          unzip dependency-check-8.4.1-release.zip -d dependency-check
          chmod +x dependency-check/bin/dependency-check.sh

      - name: Run Dependency-Check Scan
        run: dependency-check/bin/dependency-check.sh --project "auth.api" --scan . --format HTML --out dependency-check-report.html
        continue-on-error: true

      - name: List files for debug
        run: ls -lh

      - name: Upload SCA Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report.html
        continue-on-error: true

  notify-on-failure:
    name: Notify on Failure
    runs-on: ubuntu-latest
    needs: [dast, sca]
    if: failure()
    steps:
      - name: Send Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: |
            Falha no Pipeline de Segurança para *${{ github.repository }}* no workflow *${{ github.workflow }}*.
            Verifique os logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
